baseurl: /
canonifyURLs: false
disableAliases: true
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
languageCode: en-US
paginate: 7
rssLimit: 10

# Multilingual
defaultContentLanguage: en
disableLanguages:
- de
- nl
# defaultContentLanguageInSubdir: true


# add redirects/headers
outputs:
  home:
  - HTML
  - RSS
  - REDIRECTS
  - HEADERS
  section:
  - HTML
  - RSS
  - SITEMAP

# remove .{ext} from text/netlify
mediaTypes:
  text/netlify:
    suffixes:
    - ""
    delimiter: ""


outputFormats:
  REDIRECTS: # add output format for netlify _redirects
    mediaType: text/netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  HEADERS: # add output format for netlify _headers
    mediaType: text/netlify
    baseName: _headers
    isPlainText: true
    notAlternative: true
  SITEMAP: # add output format for section sitemap.xml
    mediaType: application/xml
    baseName: sitemap
    isHTML: false
    isPlainText: true
    noUgly: true
    rel: sitemap

caches:
  getjson:
    dir: :cacheDir/:project
    maxAge: 10s

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

taxonomies:
  contributor: contributors

permalinks:
  blog: /blog/:title/

minify:
  tdewolff:
    html:
      keepWhitespace: false

module:
  hugoVersion:
    extended: true
    min: 0.80.0
    max: ""
  mounts:
  - source: node_modules/@hyas/doks/archetypes
    target: archetypes
  - source: node_modules/@hyas/doks/assets
    target: assets
  - source: node_modules/@hyas/doks/data
    target: data
  - source: node_modules/@hyas/doks/layouts
    target: layouts
  - source: node_modules/@hyas/doks/static
    target: static
  - source: node_modules/flexsearch
    target: assets/js/vendor/flexsearch
  - source: node_modules/katex
    target: assets/js/vendor/katex
  - source: node_modules/mermaid
    target: assets/js/vendor/mermaid
  - source: assets
    target: assets
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: archetypes
    target: archetypes
  - source: data
    target: data
